/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[2,3],$V1=[1,5],$V2=[2,11],$V3=[5,8,10],$V4=[1,10],$V5=[1,11],$V6=[1,12],$V7=[1,13],$V8=[1,14],$V9=[1,16],$Va=[1,17],$Vb=[1,18],$Vc=[14,16,17,19,22,24,28,31,34,35,36],$Vd=[7,14,19,22,24,28,29,30,31,32,34,35,36],$Ve=[1,24],$Vf=[1,23],$Vg=[14,19,22,24,28,31,34,35,36],$Vh=[7,11,14,19,22,24,27,28,29,30,31,32,34,35,36,38,40,41,42,43,44,45,46,47,48],$Vi=[7,11,14,19,22,24,28,29,30,31,32,34,35,36,38],$Vj=[1,54],$Vk=[1,55],$Vl=[1,56],$Vm=[1,57],$Vn=[1,58],$Vo=[1,59],$Vp=[1,60],$Vq=[1,61],$Vr=[1,62],$Vs=[27,40,41,42,43,44,45,46,47,48];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"program":3,"methods":4,"BEGIN_MAIN":5,"statements":6,"END_MAIN":7,"EOF":8,"method":9,"METHOD_DECLARATION":10,"VARIABLE":11,"arguments_declared":12,"non_void":13,"END_METHOD_DECLARATION":14,"argument_declared":15,"ARG_DECLARATION":16,"NON_VOID_METHOD":17,"statement":18,"PRINT":19,"integer":20,"STRING_LITTERAL":21,"DECLARE_INT":22,"SET_INITIAL_VALUE":23,"BEGIN_ASSIGN":24,"SET_VALUE":25,"ops":26,"END_ASSIGN":27,"IF":28,"END_IF":29,"ELSE":30,"WHILE":31,"END_WHILE":32,"method_call":33,"ASSIGN_FROM_CALL":34,"RETURN":35,"CALL_METHOD":36,"arguments":37,"NUMBER":38,"op":39,"PLUS":40,"MINUS":41,"MULTIPLY":42,"DIVIDE":43,"MODULO":44,"EQUAL":45,"GREATER":46,"OR":47,"AND":48,"$accept":0,"$end":1},
terminals_: {2:"error",5:"BEGIN_MAIN",7:"END_MAIN",8:"EOF",10:"METHOD_DECLARATION",11:"VARIABLE",14:"END_METHOD_DECLARATION",16:"ARG_DECLARATION",17:"NON_VOID_METHOD",19:"PRINT",21:"STRING_LITTERAL",22:"DECLARE_INT",23:"SET_INITIAL_VALUE",24:"BEGIN_ASSIGN",25:"SET_VALUE",27:"END_ASSIGN",28:"IF",29:"END_IF",30:"ELSE",31:"WHILE",32:"END_WHILE",34:"ASSIGN_FROM_CALL",35:"RETURN",36:"CALL_METHOD",38:"NUMBER",40:"PLUS",41:"MINUS",42:"MULTIPLY",43:"DIVIDE",44:"MODULO",45:"EQUAL",46:"GREATER",47:"OR",48:"AND"},
productions_: [0,[3,6],[4,2],[4,0],[9,6],[12,2],[12,0],[15,2],[13,1],[13,0],[6,2],[6,0],[18,2],[18,2],[18,4],[18,6],[18,4],[18,6],[18,4],[18,1],[18,3],[18,2],[33,3],[37,2],[37,0],[20,1],[20,1],[26,2],[26,1],[39,2],[39,2],[39,2],[39,2],[39,2],[39,2],[39,2],[39,2],[39,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return $$[$0-5].concat($$[$0-1]).concat(new MainExpression($$[$0-3])); 
break;
case 2: case 10: case 23: case 27:
 this.$ = $$[$0-1].concat($$[$0]); 
break;
case 3: case 6: case 11: case 24:
 this.$ = []; 
break;
case 4:
 this.$ = new MethodDeclarationExpression($$[$0-4], $$[$0-3], $$[$0-1]); 
break;
case 5:
 this.$ = $$[$0-1].concat($$[$0]) 
break;
case 7: case 19:
 this.$ = $$[$0]; 
break;
case 12: case 13:
 this.$ = new PrintExpression($$[$0]); 
break;
case 14:
 this.$ = new IntDeclarationExpression($$[$0-2], $$[$0]); 
break;
case 15:
 this.$ = new AssignementExpression($$[$0-4], $$[$0-2], $$[$0-1]);
break;
case 16:
 this.$ = new IfExpression($$[$0-2], $$[$0-1]); 
break;
case 17:
 this.$ = new IfExpression($$[$0-4], $$[$0-3], $$[$0-1]); 
break;
case 18:
 this.$ = new WhileExpression($$[$0-2], $$[$0-1]); 
break;
case 20:
 this.$ = new AssignementFromCallExpression($$[$0-1], $$[$0]); 
break;
case 21:
 this.$ = new ReturnExpression($$[$0]); 
break;
case 22:
 this.$ = new CallExpression($$[$0-1], $$[$0]); 
break;
case 28:
 this.$ = [$$[$0]]; 
break;
case 29:
 this.$ = ' + ' + $$[$0]; 
break;
case 30:
 this.$ = ' - ' + $$[$0]; 
break;
case 31:
 this.$ = ' * ' + $$[$0]; 
break;
case 32:
 this.$ = ' / ' + $$[$0]; 
break;
case 33:
 this.$ = ' % ' + $$[$0]; 
break;
case 34:
 this.$ = ' == ' + $$[$0]; 
break;
case 35:
 this.$ = ' > ' + $$[$0]; 
break;
case 36:
 this.$ = ' || ' + $$[$0]; 
break;
case 37:
 this.$ = ' && ' + $$[$0]; 
break;
}
},
table: [o([5,10],$V0,{3:1,4:2}),{1:[3]},{5:[1,3],9:4,10:$V1},o([7,19,22,24,28,31,34,35,36],$V2,{6:6}),o($V3,[2,2]),{11:[1,7]},{7:[1,8],18:9,19:$V4,22:$V5,24:$V6,28:$V7,31:$V8,33:15,34:$V9,35:$Va,36:$Vb},o($Vc,[2,6],{12:19}),o([8,10],$V0,{4:20}),o($Vd,[2,10]),{11:$Ve,20:21,21:[1,22],38:$Vf},{11:[1,25]},{11:[1,26]},{11:$Ve,20:27,38:$Vf},{11:[1,28]},o($Vd,[2,19]),{11:[1,29]},{11:$Ve,20:30,38:$Vf},{11:[1,31]},o($Vg,[2,9],{13:32,15:33,16:[1,35],17:[1,34]}),{8:[1,36],9:4,10:$V1},o($Vd,[2,12]),o($Vd,[2,13]),o($Vh,[2,25]),o($Vh,[2,26]),{23:[1,37]},{25:[1,38]},o([19,22,24,28,29,30,31,34,35,36],$V2,{6:39}),o([19,22,24,28,31,32,34,35,36],$V2,{6:40}),{33:41,36:$Vb},o($Vd,[2,21]),o($Vi,[2,24],{37:42}),o($Vg,$V2,{6:43}),o($Vc,[2,5]),o($Vg,[2,8]),{11:[1,44]},{1:[2,1]},{11:$Ve,20:45,38:$Vf},{11:$Ve,20:46,38:$Vf},{18:9,19:$V4,22:$V5,24:$V6,28:$V7,29:[1,47],30:[1,48],31:$V8,33:15,34:$V9,35:$Va,36:$Vb},{18:9,19:$V4,22:$V5,24:$V6,28:$V7,31:$V8,32:[1,49],33:15,34:$V9,35:$Va,36:$Vb},o($Vd,[2,20]),o($Vd,[2,22],{20:50,11:$Ve,38:$Vf}),{14:[1,51],18:9,19:$V4,22:$V5,24:$V6,28:$V7,31:$V8,33:15,34:$V9,35:$Va,36:$Vb},o($Vc,[2,7]),o($Vd,[2,14]),{26:52,39:53,40:$Vj,41:$Vk,42:$Vl,43:$Vm,44:$Vn,45:$Vo,46:$Vp,47:$Vq,48:$Vr},o($Vd,[2,16]),o([19,22,24,28,29,31,34,35,36],$V2,{6:63}),o($Vd,[2,18]),o($Vi,[2,23]),o($V3,[2,4]),{27:[1,64],39:65,40:$Vj,41:$Vk,42:$Vl,43:$Vm,44:$Vn,45:$Vo,46:$Vp,47:$Vq,48:$Vr},o($Vs,[2,28]),{11:$Ve,20:66,38:$Vf},{11:$Ve,20:67,38:$Vf},{11:$Ve,20:68,38:$Vf},{11:$Ve,20:69,38:$Vf},{11:$Ve,20:70,38:$Vf},{11:$Ve,20:71,38:$Vf},{11:$Ve,20:72,38:$Vf},{11:$Ve,20:73,38:$Vf},{11:$Ve,20:74,38:$Vf},{18:9,19:$V4,22:$V5,24:$V6,28:$V7,29:[1,75],31:$V8,33:15,34:$V9,35:$Va,36:$Vb},o($Vd,[2,15]),o($Vs,[2,27]),o($Vs,[2,29]),o($Vs,[2,30]),o($Vs,[2,31]),o($Vs,[2,32]),o($Vs,[2,33]),o($Vs,[2,34]),o($Vs,[2,35]),o($Vs,[2,36]),o($Vs,[2,37]),o($Vd,[2,17])],
defaultActions: {36:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


function MainExpression (statements) {
	this.type = 'MainExpression';
	this.statements = statements;
}

function PrintExpression (value) {
	this.type = 'PrintExpression';
	this.value = value;
}

function IntDeclarationExpression (name, value) {
	this.type = 'IntDeclarationExpression';
	this.name = name;
	this.value = value;
}

function AssignementExpression (name, initialValue, operations) {
	this.type = 'AssignementExpression';
	this.name = name;
	this.initialValue = initialValue;
	this.operations = operations;
}

function IfExpression (predicate, ifStatements, elseStatements) {
	this.type = 'IfExpression';
	this.predicate = predicate;
	this.ifStatements = ifStatements;
	this.elseStatements = elseStatements;
}

function WhileExpression (predicate, whileStatements) {
	this.type = 'WhileExpression';
	this.predicate = predicate;
	this.whileStatements = whileStatements;
}

function MethodDeclarationExpression (name, arguments, innerStatements) {
	this.type = 'MethodDeclarationExpression';
	this.name = name;
	this.arguments = arguments;
	this.innerStatements = innerStatements;
}

function CallExpression (name, arguments) {
	this.type = 'CallExpression';
	this.name = name;
	this.arguments = arguments;
}

function ReturnExpression (value) {
	this.type = 'ReturnExpression';
	this.value = value;
}

function AssignementFromCallExpression (name, functionCalled) {
	this.type = 'AssignementFromCallExpression';
	this.name = name;
	this.functionCalled = functionCalled;
}/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespaces */
break;
case 1:return 5
break;
case 2:return 7
break;
case 3:return 38
break;
case 4:return 19
break;
case 5:return 22
break;
case 6:return 23
break;
case 7:return 24
break;
case 8:return 27
break;
case 9:return 25
break;
case 10:return 40
break;
case 11:return 41
break;
case 12:return 42
break;
case 13:return 43
break;
case 14:return 44
break;
case 15:return 45
break;
case 16:return 46
break;
case 17:return 47
break;
case 18:return 48
break;
case 19:return 28
break;
case 20:return 30
break;
case 21:return 29
break;
case 22:return 31
break;
case 23:return 32
break;
case 24:return 10
break;
case 25:return 16
break;
case 26:return 17
break;
case 27:return 14
break;
case 28:return 36
break;
case 29:return 35
break;
case 30:return 34
break;
case 31:return 11
break;
case 32:return 21
break;
case 33:return 8
break;
}
},
rules: [/^(?:\s+)/,/^(?:IT'S SHOWTIME\b)/,/^(?:YOU HAVE BEEN TERMINATED\b)/,/^(?:-?[0-9]+)/,/^(?:TALK TO THE HAND\b)/,/^(?:HEY CHRISTMAS TREE\b)/,/^(?:YOU SET US UP\b)/,/^(?:GET TO THE CHOPPER\b)/,/^(?:ENOUGH TALK\b)/,/^(?:HERE IS MY INVITATION\b)/,/^(?:GET UP\b)/,/^(?:GET DOWN\b)/,/^(?:YOU'RE FIRED\b)/,/^(?:HE HAD TO SPLIT\b)/,/^(?:I LET HIM GO\b)/,/^(?:YOU ARE NOT YOU YOU ARE ME\b)/,/^(?:LET OFF SOME STEAM BENNET\b)/,/^(?:CONSIDER THAT A DIVORCE\b)/,/^(?:KNOCK KNOCK\b)/,/^(?:BECAUSE I'M GOING TO SAY PLEASE\b)/,/^(?:BULLSHIT\b)/,/^(?:YOU HAVE NO RESPECT FOR LOGIC\b)/,/^(?:STICK AROUND\b)/,/^(?:CHILL\b)/,/^(?:LISTEN TO ME VERY CAREFULLY\b)/,/^(?:I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE\b)/,/^(?:GIVE THESE PEOPLE AIR\b)/,/^(?:HASTA LA VISTA, BABY\b)/,/^(?:DO IT NOW\b)/,/^(?:I'LL BE BACK\b)/,/^(?:GET YOUR ASS TO MARS\b)/,/^(?:[a-zA-Z]+)/,/^(?:"(?:[^"\\]|\\.)*")/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}